[build-system]
requires = ["setuptools", "setuptools_scm", "wheel", "bump2version"]
build-backend = "setuptools.build_meta"

[project]
name = "bump2v"
version = "0.0.8"

[project.scripts]
bumptydumpty = "bump2v.__main__:main"
versionkaboom = "bump2v.__main__:main"
bismillah = "bump2v.__main__:main"
bump2v = "bump2v.__main__:main"